#!/usr/bin/env python3
"""
Fine-tune the bi-encoder on our judged + synthetic pairs.

Uses MultipleNegativesRankingLoss (InfoNCE) from sentence-transformers,
which treats other queries in the same batch as in-batch negatives.

Input: data/processed/synthetic_pairs.jsonl
       (generated by generate_synthetic_pairs.py)

Output: data/processed/finetuned_biencoder/  (saved SentenceTransformer model)

Usage:
    python scripts/finetune_embeddings.py \
        --pairs data/processed/synthetic_pairs.jsonl \
        --base-model sentence-transformers/msmarco-MiniLM-L6-cos-v5 \
        --output data/processed/finetuned_biencoder \
        --epochs 3 --batch-size 32
"""

import argparse
import json
from pathlib import Path

import torch
from sentence_transformers import SentenceTransformer, InputExample
from sentence_transformers import losses
from torch.utils.data import DataLoader

BASE = Path(__file__).resolve().parent.parent


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pairs", default=str(BASE / "data/processed/synthetic_pairs.jsonl"))
    parser.add_argument("--base-model",
                        default="sentence-transformers/msmarco-MiniLM-L6-cos-v5")
    parser.add_argument("--output",
                        default=str(BASE / "data/processed/finetuned_biencoder"))
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--warmup-ratio", type=float, default=0.1)
    parser.add_argument("--min-score", type=int, default=1,
                        help="Minimum relevance score to include (default: 1)")
    args = parser.parse_args()

    print(f"Loading pairs from {args.pairs} ...")
    examples = []
    with open(args.pairs) as f:
        for line in f:
            rec = json.loads(line)
            if rec.get("score", 1) >= args.min_score:
                examples.append(InputExample(
                    texts=[rec["query"], rec["positive"]]
                ))

    print(f"  {len(examples)} training pairs loaded")
    print(f"Loading base model: {args.base_model} ...")
    model = SentenceTransformer(args.base_model)

    train_dataloader = DataLoader(examples, shuffle=True, batch_size=args.batch_size)
    train_loss = losses.MultipleNegativesRankingLoss(model)

    warmup_steps = int(len(train_dataloader) * args.epochs * args.warmup_ratio)
    print(f"Training: {args.epochs} epochs, batch={args.batch_size}, "
          f"warmup={warmup_steps} steps")

    torch.set_num_threads(16)
    model.fit(
        train_objectives=[(train_dataloader, train_loss)],
        epochs=args.epochs,
        warmup_steps=warmup_steps,
        show_progress_bar=True,
        output_path=args.output,
    )

    print(f"\nFine-tuned model saved to {args.output}")
    print("Next step: rebuild FAISS index with:")
    print(f"  python scripts/build_dense_index.py --model {args.output} "
          f"--output data/processed/faiss_finetuned.bin")


if __name__ == "__main__":
    main()
